import { PrismaClient, CuisineType, PriceRange } from '@prisma/client';

const prisma = new PrismaClient();

async function seedProdForce() {
  console.log('Starting production database seeding with production URL...');

  // Clear existing data
  await prisma.comment.deleteMany();
  console.log('Cleared existing comments');

  await prisma.restaurant.deleteMany();
  console.log('Cleared existing restaurants');

  // Create restaurants
  const restaurants = [
    {
      name: 'Shawarma Press - Johns Creek',
      address: '11600 Medlock Bridge Rd #190, Johns Creek, GA 30097',
      cuisineType: CuisineType.MEDITERRANEAN,
      description: 'Authentic Mediterranean cuisine featuring shawarma, falafel, and hummus.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Kimchi Red - Alpharetta',
      address: '11950 Jones Bridge Rd #104, Alpharetta, GA 30005',
      cuisineType: CuisineType.OTHER,
      description: 'Korean fusion restaurant offering halal options.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipOxEsVDX4NXU4HZCJyXWH_2XRQxkQYPHnWGgxI=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: "Olomi's Grill",
      address: '11600 Medlock Bridge Rd #170, Johns Creek, GA 30097',
      cuisineType: CuisineType.MEDITERRANEAN,
      description: 'Mediterranean grill specializing in kebabs and grilled meats.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: "Aachi's Indian Restaurant and Bakery",
      address: '11600 Medlock Bridge Rd #170, Johns Creek, GA 30097',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Authentic South Indian cuisine and fresh baked goods.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Spices Hut Food Court',
      address: '2089 Lawrenceville Hwy, Decatur, GA 30033',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Food court featuring various Indian and Pakistani dishes.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: false,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Pista House Alpharetta',
      address: '11105 State Bridge Rd, Alpharetta, GA 30022',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Popular Indian restaurant known for biryani and kebabs.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Namak',
      address: '2390 Chamblee Tucker Rd, Chamblee, GA 30341',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Fine dining Indian restaurant with modern ambiance.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.HIGH,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Biryani House Atlanta',
      address: '3675 Satellite Blvd, Duluth, GA 30096',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Specializing in various styles of biryani and Indian cuisine.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Al Zein Shawarma & Mediterranean Grill',
      address: '2750 Buford Hwy NE, Atlanta, GA 30324',
      cuisineType: CuisineType.MEDITERRANEAN,
      description: 'Mediterranean restaurant known for shawarma and grilled items.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Kimchi Red - Johns Creek',
      address: '11600 Medlock Bridge Rd #170, Johns Creek, GA 30097',
      cuisineType: CuisineType.OTHER,
      description: 'Korean fusion restaurant with halal options.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Cafe Efendi Mediterranean Restaurant',
      address: '1275 Powers Ferry Rd SE, Marietta, GA 30067',
      cuisineType: CuisineType.MEDITERRANEAN,
      description: 'Upscale Mediterranean dining experience.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.HIGH,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Karachi Broast & Grill',
      address: '1825 Rockbridge Rd, Stone Mountain, GA 30087',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Pakistani restaurant specializing in grilled items.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Zyka: The Taste | Indian Restaurant | Decatur',
      address: '1677 Scott Blvd, Decatur, GA 30033',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Popular Indian restaurant known for its flavorful dishes.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'The Halal Guys',
      address: '4929 Buford Hwy NE, Chamblee, GA 30341',
      cuisineType: CuisineType.MEDITERRANEAN,
      description: 'Famous for their gyro and chicken platters.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: "Khan's Kitchen",
      address: '4646 Buford Hwy NE, Chamblee, GA 30341',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Pakistani and Indian cuisine with authentic flavors.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Shibam Coffee',
      address: '2947 N Druid Hills Rd NE, Atlanta, GA 30329',
      cuisineType: CuisineType.CAFE,
      description: 'Middle Eastern coffee shop with pastries.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'MOTW Coffee and Pastries',
      address: '3097 N Druid Hills Rd, Decatur, GA 30033',
      cuisineType: CuisineType.CAFE,
      description: 'Modern coffee shop with Middle Eastern influences.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: '967 Coffee Co',
      address: '725 Ponce De Leon Ave NE, Atlanta, GA 30306',
      cuisineType: CuisineType.CAFE,
      description: 'Specialty coffee shop with Middle Eastern treats.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Baladi Coffee',
      address: '4646 Buford Hwy NE, Chamblee, GA 30341',
      cuisineType: CuisineType.CAFE,
      description: 'Traditional Middle Eastern coffee experience.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Mukja Korean Fried Chicken',
      address: '933 Peachtree St NE, Atlanta, GA 30309',
      cuisineType: CuisineType.OTHER,
      description: 'Korean fried chicken with halal options.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.MEDIUM,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Baraka Shawarma Atlanta',
      address: '3529 Buford Hwy NE, Atlanta, GA 30329',
      cuisineType: CuisineType.MEDITERRANEAN,
      description: 'Mediterranean restaurant specializing in shawarma.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: 'Botiwalla by Chai Pani',
      address: '675 Ponce De Leon Ave NE, Atlanta, GA 30308',
      cuisineType: CuisineType.INDIAN_PAKISTANI,
      description: 'Indian street food with a modern twist.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.LOW,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
    {
      name: "Dantanna's",
      address: '3400 Around Lenox Rd NE #304, Atlanta, GA 30326',
      cuisineType: CuisineType.OTHER,
      description: 'Upscale sports bar with halal options.',
      imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPXPGXAXWcHNr_hc_OXZcHWVGP_-0GVIXgHQDQ=s1360-w1360-h1020',
      priceRange: PriceRange.HIGH,
      hasPrayerRoom: false,
      hasOutdoorSeating: true,
      isZabiha: true,
      hasHighChair: true,
    },
  ];

  for (const restaurant of restaurants) {
    try {
      await prisma.restaurant.create({
        data: restaurant,
      });
      console.log(`Created restaurant ${restaurant.name}`);
    } catch (error) {
      console.error(`Error creating restaurant ${restaurant.name}:`, error);
    }
  }

  console.log('Finished seeding restaurants');
}

seedProdForce()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });